apiVersion: v1
kind: Deployment
metadata:
  name: minecraft
  namespace: minecraft
  labels:
    toolkit.fluxcd.io/tenant: dev-team
    app: minecraft
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: rlenferink/minecraft:1.19.1
        ports:
        - containerPort: 25565