apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
  namespace: minecraft
spec:
  selector:
    app.kubernetes.io/name: minecraft
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565